name: Benchmark OpenCV on RISC-V

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: opencv

    - name: Install prerequisities
      run: |
          python3 -m pip install gdown
          gdown https://drive.google.com/uc?id=1dww_ZMX68nTf5UmlDzDN3fJy4yLr2i4u
          tar -xf sc-dt-2024.09.tar.gz
          sudo cp -r sc-dt/riscv-gcc /opt/riscv
          sudo cp -r sc-dt/llvm /opt/rvv-llvm

    - name: Cross-compile OpenCV
      run: |
        cmake \
          -DCMAKE_TOOLCHAIN_FILE=$(realpath opencv/platforms/linux/riscv64-clang.toolchain.cmake) \
          -DRISCV_RVV_SCALABLE=ON \
          -DWITH_OPENCL=OFF \
          -DCPU_BASELINE_REQUIRE=RVV \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_LIST=ts,core \
          -S opencv -B opencv_build

        cmake --build opencv_build -j$(nproc --all)

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: opencv_build
        path: |
          opencv_build/bin/opencv_perf_core
          opencv_build/lib/libopencv_core*

  test:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Clean workspace
      run: |
        rm -rf ${{ github.workspace }}/*

    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        name: opencv_build

    - name: Run performance tests
      run: |
        export LD_LIBRARY_PATH=./lib:$LD_LIBRARY_PATH
        chmod +x ./bin/*
        ./bin/opencv_perf_core --gtest_output=xml:pr.xml ${{ github.event.pull_request.body }}

    - name: Run performance tests (baseline)
      run: |
        mkdir opencv_baseline && cd opencv_baseline
        python3 -m gdown https://drive.google.com/uc?id=16xJ1Kg_lG8xVIIiS63saNvsupeCKC9CF
        tar -xf opencv_rvv_baseline.tar.gz
        export LD_LIBRARY_PATH=./lib:$LD_LIBRARY_PATH
        ./bin/opencv_perf_core --gtest_output=xml:../baseline.xml ${{ github.event.pull_request.body }}

    - name: Compare
      run: |
        wget https://raw.githubusercontent.com/opencv/opencv/refs/heads/4.x/modules/ts/misc/color.py
        wget https://raw.githubusercontent.com/opencv/opencv/refs/heads/4.x/modules/ts/misc/table_formatter.py
        wget https://raw.githubusercontent.com/opencv/opencv/refs/heads/4.x/modules/ts/misc/testlog_parser.py
        wget https://raw.githubusercontent.com/opencv/opencv/refs/heads/4.x/modules/ts/misc/summary.py
        python3 summary.py baseline.xml pr.xml

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: reports
        path: |
          *.xml
